- .gitignore
- dev/README.md
- dev/sts-oidc/main.tf
Three additional permissions are needed for the operator to manage Route53 Hosted Zone records
```yaml
"route53:ChangeResourceRecordSets",
"route53:ListHostedZonesByName",
"route53:ListResourceRecordSets"
```
https://github.com/openshift/aws-vpce-operator/blob/main/pkg/aws_client/route53_hosted_zone.go
> OSD-11906 Update with needed Route53 permissions for local dev

- Makefile
- build/Dockerfile
- config/config.go
- fips.go
Moving to a Dockerfile like all the other operators instead of the default provided one.
> Dockerfile, FIPS, and config.go fixes for boilerplate

- .gitignore
- build/bin/entrypoint
- build/bin/user_setup
Needed in https://github.com/openshift/aws-vpce-operator/blob/main/build/Dockerfile#L19, seems common to all operators - not sure why it wasn't part of boilerplating the operator...
> OSD-11517 Add missing shell scripts for the Dockerfile

- Makefile
- controllers/vpcendpoint/cleanup.go
- controllers/vpcendpoint/helpers.go
- controllers/vpcendpoint/validation.go
- controllers/vpcendpoint/vpcendpoint_controller.go
- dev/README.md
- pkg/dnses/main.go
Documenting and pulling out the initialization of the `ClusterInfo` struct so that the `Reconcile` function is more clearly:
* initialize
* check for deletion/delete if needed
* create/update if needed
Adding back useful "default" operator-sdk make targets that got wiped out by boilerplate
> OSD-11517 Pull out ClusterInfo struct and initialization to improve readability

- controllers/vpcendpoint/helpers.go
- controllers/vpcendpoint/vpcendpoint_controller.go
- go.mod
Switch to adding `Request.Namespace` and `Request.Name` and use nicer timestamps, e.g. past:
```
1.6547026149781811e+09	DEBUG	controller.vpcendpoint	Searching for security group by ID	{"reconciler group": "pso.example.com", "reconciler kind": "VpcEndpoint", "name": "demo", "namespace": "demo", "id": "sg-0bc3b12b1da744606"}
```
present:
```json
{"level":"info","ts":"2022-06-08T15:15:35-04:00","logger":"vpcendpoint","caller":"vpcendpoint/cleanup.go:67","msg":"Deleting AWS resources","Request.Namespace":"demo","Request.Name":"demo","SecurityGroup":"sg-0bc3b12b1da744606"}
```
> Standardize request logging with RFC3339 timestamps

- README.md
- pkg/aws_client/client_test.go
- pkg/aws_client/subnet_test.go
A mocked `DescribeSubnets` was all that was needed
Also showing off our whopping 11% test coverage ⭐
> OSD-11948 Add unit tests for AWS subnet functions

- pkg/aws_client/client_test.go
- pkg/aws_client/subnet_test.go
- pkg/aws_client/vpc_endpoint_test.go
The unit testing march continues. In their current state, just like the subnet unit tests, they're not the most useful, but as we run into edge cases this provides a framework to add those in and validate functionality.
> OSD-11948 Add unit tests for AWS VPC Endpoint functions

- controllers/vpcendpoint/helpers.go
- controllers/vpcendpoint/helpers_test.go
- controllers/vpcendpoint/vpcendpoint_controller.go
- go.mod
- go.sum
- pkg/aws_client/mock.go
- pkg/aws_client/route53_hosted_zone_test.go
- pkg/aws_client/security_group_test.go
- pkg/aws_client/subnet_test.go
- pkg/aws_client/vpc_endpoint_test.go
- pkg/dnses/main_test.go
- pkg/infrastructures/main_test.go
- pkg/testutil/mock.go
Needed to refactor the mocks built for unit testing the `aws_client` package so that they could be used when testing the controller.
> OSD-11948 Use mocks to test controller helper functions

- Makefile
This bypasses boilerplate's production hash discovery so we can finally get a saas bundle build.
> [OSD-12247] Add temp fix for saas bundle production hash discovery

- controllers/vpcendpoint/helpers.go
- controllers/vpcendpoint/helpers_test.go
- controllers/vpcendpoint/validation.go
- main.go
- pkg/aws_client/client.go
- pkg/aws_client/mock.go
- pkg/aws_client/route53_hosted_zone.go
- pkg/aws_client/route53_hosted_zone_test.go
- pkg/aws_client/security_group.go
- pkg/aws_client/security_group_rules.go
- pkg/aws_client/security_group_rules_test.go
- pkg/aws_client/security_group_test.go
- pkg/aws_client/subnet.go
- pkg/aws_client/subnet_test.go
- pkg/aws_client/tags.go
- pkg/aws_client/tags_test.go
- pkg/aws_client/vpc_endpoint.go
- pkg/aws_client/vpc_endpoint_test.go
The meat of this change is not exporting ec2Client/route53Client (making them lowercase). This will help future developers as they'll be unable to access ec2Client/route53Client directly so that they need to implement functions in `pkg/awsclient` --> know that this operator will need new AWS permissions. Coming out of this, `CreateTags`,  `DescribeSecurityGroupRules`, and `ModifyVpcEndpoiont` were stragglers that were using the exported ec2Client and thus pulled out and simple test cases were added.
```
type AWSClient struct {
ec2Client     ec2iface.EC2API
route53Client route53iface.Route53API
}
```
> OSD-11245 Unexporting ec2Client/route53Client

- controllers/vpcendpoint/helpers.go
- controllers/vpcendpoint/helpers_test.go
- controllers/vpcendpoint/validation.go
- controllers/vpcendpoint/vpcendpoint_controller.go
- main.go
Fixing a couple bugs in the ExternalName service code:
* By writing an `OwnerReference` for the controller, the service will be deleted (verified in testing as well) when the corresponding VpcEndpoint CR is deleted. Also added some logic to update the ExternalName service in case it gets modified.
```go
if err := controllerutil.SetControllerReference(resource, svc, r.Scheme); err != nil {
return nil, err
}
```
* Added logic to update/fix the ExternalName service's `.spec.ExternalName` if it gets modified
* The generated ExternalName was using an incorrect variable
```go
// Something like com.amazonaws.us-gov-west-1.vpce.000000.cluster0000.i1.devshift.com
ExternalName: fmt.Sprintf("%s.%s", resource.Spec.ServiceName, r.clusterInfo.domainName),
// vs. splunk.cluster0000.i1.devshift.com …
```
> OSD-12362 Handle update/deletion of the ExternalName service

- api/v1alpha1/vpcendpoint_types.go
- deploy/crds/avo.openshift.io_vpcendpoints.yaml
Old version:
```
❯ k get vpcendpoint -n demo
NAME   AGE
demo   17m
```
After this PR:
```
❯ k get vpcendpoint -n demo       
NAME   STATUS      ID                       AGE
demo   available   vpce-0174ce88096d7b646   47m
```
> OSD-12245 Add AWS VPCE status and ID to `kubectl get` output

- api/v1alpha1/vpcendpoint_types.go
- controllers/vpcendpoint/cleanup.go
- controllers/vpcendpoint/metrics.go
- controllers/vpcendpoint/validation.go
- controllers/vpcendpoint/vpcendpoint_controller.go
- deploy/35_metrics_service.yaml
- deploy/35_servicemonitor.yaml
- deploy/crds/avo.openshift.io_vpcendpoints.yaml
* Adding a metric named `aws_vpce_operator_vpce_pendingAcceptance` so that we can be alerted (for now) when this operator creates a VPCE that needs to be accepted by an SRE. Eventually this will be automated, but the metric can still be used.
* Adding back the `Status` field because it gets displayed via `kubectl/oc get`
> OSD-12245 Adding a VPCE pendingAcceptance metric

- deploy/30_prom-k8s-rolebinding.yaml
- deploy/35_metrics_service.yaml
* The Prometheus RoleBinding was missing a required field: `.roleRef.apiGroup`
* The [ServiceMonitor](https://github.com/openshift/aws-vpce-operator/blob/main/deploy/35_servicemonitor.yaml#L15-L17) had a labelSelector, but the Service had no labels, whoops!
> OSD-12245 bugfixes to allow metrics to exist

- deploy/20_operator.yaml
The secret name is avo-aws-creds (https://issues.redhat.com/browse/SDA-6264) also spelled correctly on line 64/66
> OSD-12248 Fix typo

- controllers/vpcendpoint/cleanup.go
- controllers/vpcendpoint/metrics.go
- controllers/vpcendpoint/validation.go
Now that https://github.com/openshift/managed-cluster-config/pull/1233 is merged, we are free to remove the `namespace` label that is now extraneous since this CRD became cluster-scope. (Previously the `PrometheusRule` CRs in MCC modified by that PR depended on a `namespace` label to exist)
> OSD-12540 Remove now extraneous namespace label

- controllers/vpcendpoint/validation.go
- pkg/util/naming.go
- pkg/util/naming_test.go
The security groups were being reconciled to have tags of:
```go
Tags: []*ec2.Tag{
{
Key:   aws.String(clusterTagKey),
Value: aws.String(""),
},
{
Key:   aws.String(OperatorTagKey),
Value: aws.String(OperatorTagValue),
},
},
```
instead of:
```go
Tags: []*ec2.Tag{
{
Key:   aws.String(OperatorTagKey),
Value: aws.String(OperatorTagValue),
},
{
Key:   aws.String(clusterTagKey),
Value: aws.String("owned"),
},
{
Key:   aws.String("Name"),
Value: aws.String(name),
},
},
```
By setting the value of `clusterTagKey` to "", hive was failing to reap the security group when the cluster got deleted, preventing a successful deletion. Validated this by creating/accepting a VPCE in stage, seeing that the correct tags are reconciled, deleting the cluster, and verifying that the cluster successfully …
> OSD-12577 controller was reconciling security groups to an incorrect set of tags

- controllers/vpcendpoint/validation.go
- go.sum
Observed a bug where the security group ID was never getting populated in the CR's status if the controller didn't create the security group (possible during operator upgrades when a CR gets handed off from one controller to the next).
Also adding a log line for an improved debugging experience when viewing the controller logs.
> OSD-12750 Set security group ID in status

- controllers/vpcendpoint/metrics.go
- controllers/vpcendpoint/vpcendpoint_controller.go
- deploy/20_operator.yaml
- hack/olm-registry/olm-artifacts-template.yaml
By marking all secrets as optional, AVO should be able to run in STS/non-STS mode depending on the secret available
> OSD-12750 Allow AVO to run in non-STS clusters

- hack/olm-registry/olm-artifacts-template.yaml
Now that it's expected to run on non-STS clusters, unblock the SelectorSyncSet to allow deployment to non-STS clusters
> OSD-12750 Unblock deployment to non-STS clusters

- controllers/vpcendpoint/helpers.go
- hack/olm-registry/olm-artifacts-template.yaml
- pkg/aws_client/subnet.go
This was creating a policy with actions like (extra trailing comma):
```json
"Action": [
"ec2:DescribeSubnets,",
"ec2:CreateSecurityGroup,",
]
```
Giving more information on this error (it wasn't obvious what it was failing on) and leaving a TODO because there's currently no way to adjust log level on-the-fly in the current implementation:
```json
{"level":"error","ts":"2022-08-23T02:34:18Z","msg":"Reconciler error","controller":"vpcendpoint","controllerGroup":"avo.openshift.io","controllerKind":"VpcEndpoint","vpcEndpoint":{"name":"splunk"},"namespace":"","name":"splunk","reconcileID":"1a4eefc9-1299-437b-9cf7-61007c5c99ae","error":"UnauthorizedOperation: You are not authorized to perform this operation.\n\tstatus code: 403, request id: …
```
> OSD-12750 Fix typos in CredentialsRequest CR

- controllers/vpcendpoint/helpers.go
- controllers/vpcendpoint/helpers_test.go
- controllers/vpcendpoint/validation.go
- controllers/vpcendpoint/validation_test.go
- pkg/testutil/mock.go
Continuing the march for test coverage in `validation.go`, this time unit tests for validating the ExternalName service
> OSD-12962 Add unit tests for ExternalName service validation

- controllers/vpcendpoint/cleanup.go
- controllers/vpcendpoint/helpers.go
- controllers/vpcendpoint/helpers_test.go
- controllers/vpcendpoint/validation.go
- controllers/vpcendpoint/validation_test.go
- pkg/aws_client/mock.go
- pkg/aws_client/vpc_endpoint.go
- pkg/aws_client/vpc_endpoint_test.go
[validateVPCEndpoint](https://github.com/openshift/aws-vpce-operator/blob/049e1a9a0feecd1fc96857511c29deb533a2d5b5/controllers/vpcendpoint/validation.go#274) is a notoriously lengthy and involved function, trumped only by `validateSecurityGroup` which is next on the list.
This PR is a slight refactor to make the code unit-test-able by pulling out some code into helper functions from `validation.go` to `helpers.go`. Unit tests were then added to `helpers_test.go` for those pieces and then a happy path unit test was added for `validateVPCEndpoint`
> OSD-12962 Add unit tests for VPCE validation

- controllers/vpcendpoint/helpers.go
- controllers/vpcendpoint/helpers_test.go
- controllers/vpcendpoint/validation.go
- controllers/vpcendpoint/validation_test.go
- pkg/aws_client/mock.go
- pkg/aws_client/security_group_test.go
Pulled out `findOrCreateSecurityGroup` from `validateSecurityGroup` and standardized it with `findOrCreateVpcEndpoint`
> OSD-12962 findOrCreateSecurityGroup unit test

- controllers/vpcendpoint/helpers.go
- controllers/vpcendpoint/helpers_test.go
- controllers/vpcendpoint/validation.go
- controllers/vpcendpoint/validation_test.go
- pkg/aws_client/mock.go
- pkg/aws_client/security_group_rules_test.go
- pkg/aws_client/tags_test.go
This leaves `controllers/vpcendpoint/cleanup.go` as pretty much the last bastion to unit test
> OSD-12962 Finish breaking apart `validateSecurityGroup` to enable unit testing

- controllers/vpcendpoint/cleanup.go
- controllers/vpcendpoint/cleanup_test.go
- controllers/vpcendpoint/vpcendpoint_controller.go
- pkg/aws_client/mock.go
- pkg/aws_client/security_group_test.go
- pkg/aws_client/vpc_endpoint_test.go
Covering the `cleanup.go` as the last little piece that wasn't under some unit test coverage.
> OSD-12962 unit testing cleanup functionality

- deploy/20_operator.yaml
Generally good defaults that other operators in commercial have, e.g. MNMO https://github.com/openshift/managed-node-metadata-operator/blob/main/deploy/20_operator.yaml#L17-L26. This operator had a toleration for infra nodes, but no affinity, so this will help push it to be scheduled on infra nodes.
> OSD-12962 Run as nonroot and help schedule on infra nodes

- deploy/20_operator.yaml
- main.go
Addresses [OSD-12964](https://issues.redhat.com/browse/OSD-12964)
- updates the readiness and liveness probes to check that the AWS auth secrets exist otherwise it cannot create a VPC Endpoint, this should fail the pod before it tries to reconcile a CR.
- since the type of creds required varies on STS or not, the check looks for both and passes as long as one of them is successful.
- Adds security context configuration that explicity sets what appears to be defaults. This is to address warnings I saw on deploying to a 4.11 cluster.
```shell
W0906 15:50:34.753365   64831 warnings.go:70] would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "aws-vpce-operator" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container …
```
> update probes and add securityContext settings to address warnings

- PROJECT
- api/v1alpha1/vpcendpoint_types.go
- controllers/vpcendpoint/cleanup.go
- controllers/vpcendpoint/helpers.go
- controllers/vpcendpoint/helpers_test.go
- controllers/vpcendpoint/metrics.go
- controllers/vpcendpoint/validation.go
- controllers/vpcendpoint/validation_test.go
- controllers/vpcendpoint/vpcendpoint_controller.go
- deploy/crds/avo.openshift.io_vpcendpoints.yaml
Essentially a revert of https://github.com/openshift/aws-vpce-operator/pull/36 to allow this operator to be more flexibly used in HyperShift.
Additionally, `.spec.externalNameService.namespace` has been removed as the expectation is now that the `ExternalName` service must be in the same namespace as the VPCE CR.
> OSD-13108 Convert VPCE to be a namespaced CRD

- deploy/20_operator.yaml
- scc settings in the deployment are not fully compatible with workloads in 4.10 clusters. As its not required or making any changes, stripping this out for now.
> strips scc settings as it breaks deployments in 4.10 and is not required

- hack/olm-registry/olm-artifacts-template.yaml
For [OSD-13345](https://issues.redhat.com/browse/OSD-13445)
- Adds the configmap needed to enable the VPC Acceptance controller in AVO
- Adds a bool to allow turning this setting on or off in App interface so changes can be tested on individual hives in non-prod first
> OSD-13445 update olm template for VPC acceptance config

- hack/olm-registry/olm-artifacts-template.yaml
saasherder in app interface does not like bools, this updates the ENABLE_VPC_ACCEPTANCE var to be a string value, so that A-I can use strings as well. This matches similar method used in [AAO](https://github.com/openshift/aws-account-operator/blob/master/hack/olm-registry/olm-artifacts-template.yaml#L41) as well. The code does not need to be changed to use a string as AAO still uses a bool in the config as well
> updates new vpc acceptance var to a string value

- main.go
For [OSD-13445](https://issues.redhat.com//browse/OSD-13445)
- Adds AAO package to Scheme in order to access AAO CR's for vpce acceptance
Why:
When testing VpcEnpointAcceptance reconciliation, the controller throws errors saying `no kind is registered for the type v1alpha1.AccountList`. AVO is attempting to list the Account CR's available through AAO but does not know what that object is. Adding it to the scheme should make list Accounts available to the controller. 
[See Comment](https://issues.redhat.com/browse/OSD-13445?focusedCommentId=21134909&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-21134909) in Jira for more  details
> OSD-13445: adds AAO to scheme to allow for listing Accounts

- README.md
- deploy/15_clusterrole.yaml
- dev/vpce_acceptance_example.yml
For [OSD-13445](https://issues.redhat.com//browse/OSD-13445),
- fixes the role used by the operator, it was missing the `watch` function, and also the object was incorrect, it needed to be `accounts` not `account` 
- adds example vpce acceptance object and info in the README for use
The role has been tested in integration and I am able to successfully auto-accept the vpce endpoint for splunk, just had to make the role change first. This is to finalize that.
> OSD-13445: updates clusterrole and README for acceptance object

- hack/olm-registry/olm-artifacts-template.yaml
For [OSD-13445](https://issues.redhat.com/browse/OSD-13445)
- updates the olm template to use a separate SelectorSyncSet for the AVO configmap this way we can target fedramp hives exclusively and not deploy this config to non-hive clusters or any commercial clusters if being tested there until desired
- this config is required to enable the second controller for VPC Endpoint acceptance to be functional
- the actual AVO config is already validated as working, this is to prevent us from enabling the second controller on customer clusters as its not usable there
- validation of the feature/config working in jira card
> OSD-13445: updates olm template for avo config on hive only

- README.md
- hack/olm-registry/olm-artifacts-template.yaml
- Removes the AvoConfig ConfigMap from olm template as this is being moved into FR App Interface using Namespace files
- Updates the README to highlight the locations of various configurations for this operator for the FedRAMP environment
> updates olm template to remove avo config

- controllers/util/util.go
- controllers/util/util_test.go
- deploy/20_operator.yaml
- main.go
[OSD-13739](https://issues.redhat.com//browse/OSD-13739)
Related to #56, this moves the checks into Go to remove the dependency on bash and puts back the default (previously thought of as useless) livenessProbe.
The livenessProbe does have value if this operator ever panics/gets killed - in the current setup the livenessProbe would continue passing as long as environment variables were set. Putting the default one back allows Kubernetes to notice and cycle the pod in this scenario instead. Validated this works in an integration environment.
> Refactor env var checks into Go

- controllers/vpcendpointacceptance/vpcendpointacceptance_controller.go
- pkg/aws_client/client.go
- pkg/aws_client/mock.go
- pkg/aws_client/vpc_endpoint_service.go
- pkg/aws_client/vpc_endpoint_service_test.go
Per OSD-13743, the `vpceacceptance` controller has been spinning when there are no vpc endpoints to accept:
```json
{"level":"error","ts":"2022-11-10T15:04:20Z","msg":"Reconciler error","controller":"vpcendpointacceptance","controllerGroup":"avo.openshift.io","controllerKind":"VpcEndpointAcceptance","vpcEndpointAcceptance":{"name":"osd-fr-splunk-acceptance-uge","namespace":"openshift-aws-vpce-operator"},"namespace":"openshift-aws-vpce-operator","name":"osd-fr-splunk-acceptance-uge","reconcileID":"82957471-cad6-45b1-84af-f1bed5e31634","error":"operation error EC2: AcceptVpcEndpointConnections, 1 validation error(s) found.\n- missing required field, AcceptVpcEndpointConnectionsInput.VpcEndpointIds.\n","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processN …
```
> Correctly handle case when no vpce need accepting

- README.md
- controllers/vpcendpoint/helpers.go
- controllers/vpcendpoint/helpers_test.go
- pkg/aws_client/mock.go
- pkg/aws_client/subnet.go
- pkg/aws_client/subnet_test.go
Per OSD-13916, we don't really need the `kubernetes.io/role/internal-elb` tag because:
* For PrivateLink clusters, only the private subnets have this tag
* For non-BYOVPC clusters, we can rely on hive to tag `kubernetes.io/role/internal-elb` correctly
* This makes the operator attach VPCEs to private + public subnets for BYOVPC, non-PrivateLink clusters, but I think that's ok. It just makes traffic from their public subnets also go through the VPCE instead of an IGW.
* (Maybe most importantly) we just can't count on end-users to tag their VPC correctly
> Remove additional required tag: `kubernetes.io/role/internal-elb`

- controllers/vpcendpointacceptance/metrics.go
- controllers/vpcendpointacceptance/vpcendpointacceptance_controller.go
This PR is part of [OSD-12965](https://issues.redhat.com/browse/OSD-12965). There is a metric defined to indicate VPCE connections that haven't been accepted
> Adding VPCE Connection Acceptance metrics

- hack/olm-registry/olm-artifacts-template.yaml
For management/service clusters, only deploy AVO SSS if they are PrivateLink as well
> Only deploy to privatelink mgmt/service clusters

- hack/olm-registry/olm-artifacts-template.yaml
The SSS is currently failing to roll out due to:
```
[2022-12-15 16:12:53] [INFO] [openshift_base.py:apply:329] - ['apply', 'hive-stage-01', 'cluster-scope', 'SelectorSyncSet', 'aws-vpce-operator']
[2022-12-15 16:12:55] [INFO] [openshift_base.py:apply:329] - ['apply', 'hive-stage-01', 'cluster-scope', 'SelectorSyncSet', 'aws-vpce-operator-svc-sss']
[2022-12-15 16:13:56] [ERROR] [openshift_base.py:_realize_resource_data:638] - [hive-stage-01/cluster-scope] [https://api.hive-stage-01.n1u3.p1.openshiftapps.com:6443/]: The SelectorSyncSet "aws-vpce-operator-svc-sss" is invalid: spec.clusterDeploymentSelector.matchExpressions[1].values: Invalid value: "string": spec.clusterDeploymentSelector.matchExpressions[1].values in body must be of type array: "string"
(error details: …
```
> OLM template syntax bugfix

- README.md
- api/v1alpha1/vpcendpoint_types.go
- controllers/vpcendpoint/helpers.go
- controllers/vpcendpoint/validation.go
- controllers/vpcendpoint/vpcendpoint_controller.go
- deploy/crds/avo.openshift.io_vpcendpoints.yaml
- dev/vpce_hosted_zone_example.yml
- pkg/aws_client/client.go
- pkg/aws_client/route53_hosted_zone.go
- pkg/aws_client/tags.go
- pkg/util/naming.go
New field added to the VPCE spec to support AVO's creation and tagging of route53 additional hosted private zones.
> OSD-13509: AVO support to create private zones

- pkg/aws_client/client.go
- pkg/util/naming.go
Updates the tags to EC2 and R53 Zones, removing an unused GetHostedZone function from the AvoRoute53API interface.
> Additional tags on EC2 and R53 resources created by AVO

- main.go
Breaking this piece out of #95, I was observing that errors in logs always contain stack traces to controller-runtime which are never relevant (they never include the line of our own code that's failing, so they don't help with debugging).
This bug is noted upstream: https://github.com/kubernetes-sigs/kubebuilder/issues/1593 and this PR implements the described workaround.
> OSD-13910 Remove misleading controller-runtime stacktraces from errors

- hack/olm-registry/olm-artifacts-template.yaml
[OSD-13910](https://issues.redhat.com//browse/OSD-13910)
We were missing:
* `ec2:DescribeVpcs`
* `route53:ListHostedZonesByVPC`
* `route53:ListTagsForResource`
* `route53:GetHostedZone`
* `route53:CreateHostedZone`
* `route53:DeleteHostedZone`
* `route53:ChangeTagsForResource`
And this dangling/unused rolebinding has been hanging out for a while.
> Add missing AWS IAM to cloud-credential operator

- deploy/15_clusterrole.yaml
- deploy/30_prometheus_role.yaml
- deploy/30_prometheus_rolebinding.yaml
[OSD-13910](https://issues.redhat.com//browse/OSD-13910) This PR addresses two K8s RBAC errors relating to AVO:
The first is from Prometheus pods (`openshift-monitoring/prometheus-k8s-*`) that cannot scrape AVO metrics which seemingly was mistakenly removed in #42:
```
ts=2023-01-22T13:37:34.598Z caller=klog.go:108 level=warn component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:541: failed to list *v1.Endpoints: endpoints is forbidden: User \"system:serviceaccount:openshift-monitoring:prometheus-k8s\" cannot list resource \"endpoints\" in API group \"\" in the namespace \"openshift-aws-vpce-operator\""
```
and the second is from AVO itself where it cannot create events, which was new functionality in #95:
```
E0124 …
```
> Missing K8s RBAC

- api/v1alpha2/vpcendpoint_types.go
- api/v1alpha2/zz_generated.deepcopy.go
- controllers/vpcendpoint/helpers.go
- deploy/17_role.yaml
- deploy/18_rolebinding.yaml
- deploy/crds/avo.openshift.io_vpcendpoints.yaml
- pkg/secrets/secrets.go
- pkg/secrets/secrets_test.go
[OSD-13906](https://issues.redhat.com//browse/OSD-13906)
This PR adds an optional `AWSCredentialOverrideRef` which allows for the operator to use specific secrets to override AWS credentials (for example, to create AWS resources in a separate AWS Account)
Note that this requires the controller to be able to read secrets in all namespaces...
> AWSCredentialOverrideRef implementation

- pkg/secrets/secrets.go
- pkg/secrets/secrets_test.go
[OSD-13907](https://issues.redhat.com//browse/OSD-13907) The following error was happening when attempting to use the AWS credential override:
```
{"level":"error","ts":"2023-01-27T18:30:10Z","msg":"Reconciler error","controller":"vpcendpoint","controllerGroup":"avo.openshift.io","controllerKind":"VpcEndpoint","VpcEndpoint":{"name":"avo-sc-test","namespace":"openshift-aws-vpce-operator"},"namespace":"openshift-aws-vpce-operator","name":"avo-sc-test","reconcileID":"5dad7071-549c-4136-9fa4-fed776605e88","error":"failed to describe subnets: operation error EC2: DescribeSubnets, exceeded maximum number of attempts, 3, https response error StatusCode: 0, RequestID: , request send failed, Post \"https://ec2.us-east-2.amazonaws.com/\": net/http: invalid header field value for \"Authorization\""} …
```
> No need to base64 decode secret data with client-go

- controllers/vpcendpoint/helpers.go
[OSD-13906](https://issues.redhat.com//browse/OSD-13906)
This function has a bug the first time it runs because the Hosted Zone doesn't exist yet (it needs to be created) and caused the controller to get stuck in a loop printing out `no hosted zone found associated to VPC: %s in region: %s` because of it.
We were deploying additional Route53 Private Hosted Zones to VPCs that already had other Route 53 Private Hosted Zones associated with them, so there were always >= 1. In some cases, especially when using `awsCredentialOverrideRef`, there may not be any pre-existing associated Private Hosted Zones.
> Fix bug where AVO was not creating a hosted zone the first time

- controllers/vpcendpoint/helpers.go
For [OSD-15012](https://issues.redhat.com//browse/OSD-15012) when we autodiscover subnets, we need to filter away any subnets in availability zones that the VPC Endpoint Service doesn't support, which is crucial in cases like `us-east-1`, where there are 6 availability zones.
* This feature requires a new permission: `ec2:DescribeVpcEndpointServices`
* While adding that in `pkg/aws_client/client.go` I noticed we are not using `ec2:DeleteTags` nor `ec2:DescribeTags`
> Filtering autodiscovered subnets by availability zones supported by the VPCE Service

- designs/vpc_load_balancing.md
[OSD-15012](https://issues.redhat.com//browse/OSD-15012) We need AVO to be able to load balance VPC Endpoints across a list of provided VPCs (respecting quota limits on the VPCs)
> Add design doc around VPC load balancing 

- README.md
- hack/olm-registry/olm-artifacts-template.yaml
If you search the codebase it's not present anywhere, it must be a relic of the past.
> Remove unused ec2:DescribeVpcs permission

- hack/olm-registry/olm-artifacts-template.yaml
We were maintaining essentially a duplicate SSS for service and management clusters.
Concerns:
* I don't have 100% confidence on what the behavior of this PR will be in practice, especially around whether I will need to manually delete the old `aws-vpce-operator-mgmt-sss` and `aws-vpce-operator-svc-sss` resources from Hive/whether it will initially clash with the new `aws-vpce-operator-hypershift-sss` resource. However, I think this is a safe learning opportunity since it'll be stage.
> Consolidate management and service cluster SSS

- Makefile
- controllers/util/util.go
- controllers/vpcendpoint/vpcendpoint_controller.go
- controllers/vpcendpointacceptance/vpcendpointacceptance_controller.go
- dev/README.md
- go.mod
* Adjusting `make run` to match upstream Operator-SDK https://github.com/operator-framework/operator-sdk/blob/master/website/content/en/docs/building-operators/golang/references/logging.md#setting-flags-when-running-locally
* This change mainly focuses on addressing a long-standing TODO where debug logs were effectively impossible to print. This is now possible with `make run ARGS="--zap-log-level=debug"` as well as by applying these flags in the deployment YAML (as well as any of the default flags described in https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/log/zap#Options.BindFlags)
* We no longer need to manually add `Request.Name` and `Request.Namespace` to the logger, they're there by default!
This allows us to get rid of our hand-rolled default logger.
Logs now look like this …
> [OSD-15012] Use controller-runtime logging functionality over hand-rolling

- api/v1alpha2/vpcendpoint_types.go
- controllers/vpcendpoint/helpers.go
- controllers/vpcendpoint/helpers_test.go
- controllers/vpcendpoint/validation.go
- controllers/vpcendpoint/vpcendpoint_controller.go
- deploy/crds/avo.openshift.io_vpcendpoints.yaml
[OSD-15012](https://issues.redhat.com//browse/OSD-15012)
This PR takes `vpcId` out of the `clusterInfo` struct and places it as a status field on the VPCEndpoint CR. This is a bit of a no-op in the other scenarios, but is a must when using VPC load-balancing since the least-used VPC may continuously change across reconcile loops. By storing this on the VPCEndpoint CR, this will allow it to remain constant after being set the first time.
> Store VPC ID in status so that it does not need to be continually detected

- README.md
- hack/olm-registry/olm-artifacts-template.yaml
[OSD-15112](https://issues.redhat.com//browse/OSD-15112)
I made a mistake and removed this in #111 - even though there is no `ec2:DescribeVpcs` in our code base, `route53:ListHostedZonesByVPC` makes this call under the hood.
```json
{"level":"error","ts":"2023-02-07T18:57:52Z","msg":"Reconciler error","controller":"vpcendpoint","controllerGroup":"avo.openshift.io","controllerKind":"VpcEndpoint","VpcEndpoint":{"name":"avo-mc-to-sc","namespace":"openshift-aws-vpce-operator"},"namespace":"openshift-aws-vpce-operator","name":"avo-mc-to-sc","reconcileID":"57117304-e039-4467-8ae1-a2b419fdce26","error":"operation error Route 53: ListHostedZonesByVPC, https response error StatusCode: 403, RequestID: 95ce100a-923d-4874-bda6-bdba9cb84550, api error AccessDenied: Failed to verify the given VPC by …
```
> Add back ec2:DescribeVpcs, which is needed by route53:ListHostedZonesByVPC

- pkg/aws_client/subnet.go
Small edge-case noticed when validating OSD-15012, but AVO can get stuck if it's searching for subnets with an empty tag-key:
```json
{"level":"error","ts":"2023-02-08T19:58:55Z","msg":"Reconciler error","controller":"vpcendpoint","controllerGroup":"avo.openshift.io","controllerKind":"VpcEndpoint","VpcEndpoint":{"name":"avo-privatelink-to-mc","namespace":"openshift-aws-vpce-operator"},"namespace":"openshift-aws-vpce-operator","name":"avo-privatelink-to-mc","reconcileID":"75fd7895-325d-4fb2-a8b2-ff25473cc834","error":"failed to reconcile VPC Endpoint subnets: failed to find subnets with tag key: "}
```
> Ignore empty tag keys as they are invalid input for our purposes

- hack/tests/avo-acceptance-test.yaml
Removes the image tag from the avo-acceptance-test.yaml. 
This value is auto generated to match the currrent repo's SHA.
> PD - Remove auto generated image tag from test yml

- hack/tests/avo-acceptance-test.yaml
This PR fixes an erorr when creating the pipeline. 
Swapping out the job name to be:
$ {JOBNAME}-${IMAGE_TAG}-${JOBID}
The Job "4bpad84-saas-avo-test-${IMAGE_TAG}" is invalid: metadata.name: Invalid value: "4bpad84-saas-avo-test-${IMAGE_TAG}". This field must adhere to DNS-1123 subdomain names spec.More info can be found at https://kubernetes.io/docs/concepts/overview/working-with-objects/names/.
> PD - Fix Job Prefix Error

- hack/tests/avo-acceptance-test.yaml
This PR adds the following functionality to SAAS-AVO-TEST:
1. Grabs the Managed and Service Clusters that are managed in a Hive Cluster. 
2. Grabs the kubeconfig of those cluster in order to oc. 
3. Checks the CSV inside each cluster to verify the SSS matches the latest SHA and succeeded updating. 
4. Checks that all clusters updated else fails the pipeline.
> PD - Add SSS update success check

- hack/olm-registry/olm-artifacts-template-fedramp.yaml
This template will be used for applying directly to Hive clusters using an App Interface namespace file. Since the Namespace file in App Interface is ensuring the namespace, having the namespace defined here is extra and AppSRE would prefer the namespace not be managed in both places.
The namespace in the SSS for all other clusters is kept since this is deployed to non-hives as well, and the namespace file does not ensure the namespace for anything but the hive cluster it targets.
> removes namespace from direct deployment

- controllers/vpcendpoint/helpers.go
- controllers/vpcendpoint/helpers_test.go
`resource.Status.ResourceRecordSet` is the full DNS name, e.g. `splunk.cluster.domain.com`, but the code currently additionally prepends the hostname again, resulting in `splunk.splunk.cluster.domain.com`.
This is what I get for commenting out a test and forgetting to fix it and add it back after the v1alpha2 refactor.
> Fix bug where externalName service was repeating itself in the DNS name

- controllers/vpcendpoint/helpers.go
- controllers/vpcendpoint/validation.go
This adds the necessary IP ranges when there is no source SG. Also added better error messaging when adding rules fails.
[OSD-15465](https://issues.redhat.com/browse/OSD-15465)
> Add IP Range when no Source Security Group Available

- hack/olm-registry/olm-artifacts-template.yaml
- Reverts changes to base OLM template made in [ae27bf0](https://github.com/openshift/aws-vpce-operator/commit/ae27bf0e9d8a5975e7fd283f82b26632834c852b) as it was realized promoting the template with hives removed would remove the operator from hive and delete the namespace which we absolutely dont want. 
- More details on why in bullet point 4 of [this comment](https://issues.redhat.com/browse/OSD-15146?focusedId=21859064&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-21859064), we will need to gradually change this SSS and promote to all regions to orphan things we don't want to manage on Hives using the base SSS template anymore.
> OSD-15146: revert changes to fedramp sss template

- controllers/vpcendpoint/helpers.go
[OSD-15465](https://issues.redhat.com//browse/OSD-15465)
When filtering VPCs by tag, it's very similar to filtering by IDs, we're load balancing across them. This fixes the bug introduced in #147
> Fix bug when load balancing VPCs by tag

- controllers/vpcendpoint/helpers.go
- pkg/aws_client/vpc_endpoint.go
```json
{"level":"debug","ts":"2023-03-20T21:24:01Z","logger":"controller.VpcEndpoint","msg":"Found infrastructure name:","controller":"vpcendpoint","controllerGroup":"avo.openshift.io","controllerKind":"VpcEndpoint","VpcEndpoint":{"name":"service-cluster-endpoint","namespace":"openshift-aws-vpce-operator"},"namespace":"openshift-aws-vpce-operator","name":"service-cluster-endpoint","reconcileID":"46cc7b16-4208-40d6-aa36-47e17d4187d2","name":"hs-sc-ge77jaj60-cw28q"}
{"level":"debug","ts":"2023-03-20T21:24:01Z","logger":"controller.VpcEndpoint","msg":"Found cluster tag:","controller":"vpcendpoint","controllerGroup":"avo.openshift.io","controllerKind":"VpcEndpoint","VpcEndpoint":{"name":"service-cluster-endpoint","namespace":"openshift-aws-vpce-operator"},"namespace":"openshift-aws-vpce-opera …
```
> Improve logging to help isolate a bug

- pkg/aws_client/client_test.go
- pkg/aws_client/vpc_endpoint.go
- pkg/aws_client/vpc_endpoint_test.go
[OSD-15465](https://issues.redhat.com//browse/OSD-15465)
The bug where AVO would select a VPC of "" occurs when all provided VPC IDs have 0 VPC Endpoints in them. This is because the map `vpcePerVpc` was previously never initialized to set the initial count for all VPC's to 0 - so when no VPC Endpoints are found with a call to `DescribeVpcEndpoints`, the map was completely empty and `minVpcId` remained at its default value, empty string.
This PR fixes this by defaulting the initial count for all VPC's to 0, defaulting `minVpcId` to the first supplied VPC ID, and unit testing this.
> Fix bug with load balancing when there are 0 VPC Endpoints

- api/v1alpha2/vpcendpoint_types.go
- controllers/vpcendpoint/helpers.go
- controllers/vpcendpoint/helpers_test.go
- deploy/crds/avo.openshift.io_vpcendpoints.yaml
This adds .spec.securityGroup.*Rules.CidrIp so that the created security group rules can optionally allow a target IPv4 CIDR range instead of only being allowed for the cluster's own master and worker security groups. If a CIDR range is specified, it will take precendence and be used, while the cluster's own master and worker security groups act as a fallback default.
Basically adds flexibility to the hardcoded `0.0.0.0/0` that was added in #144 
[OSD-15465](https://issues.redhat.com//browse/OSD-15465)
> Add ability to configure CidrIP of security group rules

- controllers/vpcendpoint/helpers.go
This happens when a security group rule does not have an allowed CidrIp:
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x21ff0c2]
goroutine 361 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:118 +0x1f4
panic({0x247b640, 0x3aa9270})
/usr/lib/golang/src/runtime/panic.go:884 +0x212
github.com/openshift/aws-vpce-operator/controllers/vpcendpoint.(*VpcEndpointReconciler).generateMissingSecurityGroupRules(0xc0003004e0, {0x2b75318, 0xc0004fe3f0}, 0xc000510400, 0xc00053e000) …
```
> Fix nil-pointer exception bug

- pkg/aws_client/vpc_endpoint.go
The loop was always picking a new VPC ID even if it wasn't really a minimum...whoops. This explains the sporadic test failures, e.g. https://github.com/openshift/aws-vpce-operator/pull/153#issuecomment-1478159504
> Fix logic error with finding the VPC ID with the minumum number of VPC Endpoints

- controllers/vpcendpoint/cleanup.go
- controllers/vpcendpoint/helpers.go
[OSD-15146](https://issues.redhat.com//browse/OSD-15146)
While migrating from v1alpha1 to v1alpha2, it was noticed that AVO reconciles away all the subnets of the VPC Endpoint in AWS, then eventually fails when executing generateRoute53Record() as there are no subnets attached to the VPC Endpoint, so it does not have any DNS names.
This commit handles the edge case by allowing that function to return without error when the VpcEnpoint CR is deleting and adds additional safeguards to ensure .status.hostedZoneId is populated before attempting to delete Route53 Record Sets.
> Handle edge cases when replacing v1alpha1 VpcEndpoints with v1alpha2

- osde2e/aws_vpce_operator_tests.go
Currently [postsubmit e2e test prow job](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/branch-ci-openshift-aws-vpce-operator-main-stage-e2e-harness/1644050248361840640) times out and fails to return results since there are no tests in the test file. Added an empty test assertion to dry run the e2e harness.
[sdcicd-888](https://issues.redhat.com//browse/sdcicd-888)
> empty ginkgo assertion  for osde2e prow job

- hack/olm-registry/olm-artifacts-template.yaml
This is the beginning of multiple steps to remove Hives from the SSS in FedRAMP so that they can be promoted separately since they have their own specific configuration and settings that will require testing in non-prod at times. We want to test hive changes in non-prod without having to promote to prod to get changes on Hive. The steps to remove hives will be as follows:
1. update the SSS to upsert and promote to all regions (This PR)
2. Update SSS to ignore Hives and promote to all regions (orphaning AVO objects on hives from SSS)
3. Change SSS back to sync and promote to all regions
Remaining work will be to add the new Hive saas files in FedRAMP for Prod once they are removed from SSS
> OSD-15146: updates fedramp sss to upsert to allow for removal of hives later

- hack/olm-registry/olm-artifacts-template.yaml
Now that AVO on Hives has been orphaned thanks to previous promotions, this template is no longer managing hives and changing back to `Sync` is safe which is the original desired setting. It was merely changed to prevent deletion of AVO from Hives during the saas migration process.
[Validation showing](https://issues.redhat.com/browse/OSD-15146?focusedId=22091021&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-22091021) AVO is no longer referenced in clustersyncs for Hive clusters nor updated from promotion, changing this to sync will not delete AVO from hives since they are no longer managed.
> changes the olm template back to the desired sync version

- controllers/vpcendpoint/vpcendpoint_controller.go
- deploy/15_clusterrole.yaml
This was forgotten during the changes in #171 where the VpcEndpoint controller was re-tooled to read a VPC Endpoint Service name from a `hypershift.openshift.io` `awsendpointservice` CR
> Add K8s RBAC for reading hypershift awsendpointservices

- hack/olm-registry/olm-artifacts-template-fedramp.yaml
- hack/olm-registry/olm-artifacts-template.yaml
This commit specifies .spec.grpcPodConfig.nodeSelector and .spec.grpdPodConfig.tolerations to schedule this operator's registry pod to infra nodes when possible.
[OSD-6629](https://issues.redhat.com//browse/OSD-6629)
> Prefer scheduling registry pod onto infra nodes

- api/v1alpha2/vpcendpoint_types.go
- controllers/vpcendpoint/helpers.go
- deploy/crds/avo.openshift.io_vpcendpoints.yaml
- deploy/crds/avo.openshift.io_vpcendpointtemplates.yaml
Enum validation was already put in place to only allow `.metadata.namespace` https://github.com/openshift/aws-vpce-operator/blob/main/api/v1alpha2/vpcendpoint_types.go#L149, however the documentation/backend code was incorrectly acting as if `.metadata.name` was the only allowed option.
This PR fixes the bug and also returns an error now if an unsupported option is supplied.
[OSD-15666](https://issues.redhat.com//browse/OSD-15666)
> .metadata.namespace is the only supported fieldPath

- controllers/vpcendpoint/helpers.go
- controllers/vpcendpointtemplate/const.go
- controllers/vpcendpointtemplate/vpcendpointtemplate_controller.go
- pkg/aws_client/route53_hosted_zone.go
- pkg/hostedcontrolplanes/hostedcontrolplanes.go
- pkg/hostedcontrolplanes/hostedcontrolplanes_test.go
The individual commits in this PR correspond to:
* Deleting a `VpcEndpointTemplate` wasn't waiting for the child `VpcEndpoints` to be deleted (and deletion wasn't even working). A finalizer was added and the deletion code was fixed.
* The DNS hostname of a hosted cluster's API Server was being read from an incorrect location on the `hostedcontroplane` CR
* The AWS Route53 API is pretty inconsistent with where it wants a Hosted Zone id vs one like `/hostedzone/${id}` and we were getting it wrong in some places
* The VpcEndpointTemplate controller is pretty spammy with a specific log line as it processes each `hostedcluster`, so I've moved that to the debug log level.
* VPC/Subnet auto-selection wasn't accounting for the possibility of there being viable subnets across different VPCs …
> Fixing bugs that have become obvious since adding the VpcEndpointTemplate

- controllers/vpcendpoint/cleanup.go
- controllers/vpcendpoint/helpers.go
- pkg/hostedcontrolplanes/hostedcontrolplanes.go
- pkg/hostedcontrolplanes/hostedcontrolplanes_test.go
This PR grabs the infra id from the `hostedcontrolplane` CR when `Spec.CustomDns.Route53PrivateHostedZone.DomainNameRef.ValueFrom.HostedControlPlaneRef` is filled out. This results in the correct behavior of one VPCE being created per `hostedcluster` as previously the VPCE's were being created based on the underlying management cluster's infra id.
Furthermore, the domain name on the `hostedcontrolplane` CR already contains the subdomain "api", so updated the parsing logic so that the subdomain is omitted when determining the base domain for the private Route53 hosted zone. The result is a clean creation/deletion flow of `VpcEndpointTemplate`s without leaking resources in Route53!
[OSD-15666](https://issues.redhat.com//browse/OSD-15666)
> Fix logic preventing creation of Route53 Hosted Zones + VPC Endpoints per HostedCluster

- api/v1alpha2/vpcendpoint_types.go
- controllers/vpcendpoint/helpers.go
- controllers/vpcendpoint/helpers_test.go
- controllers/vpcendpoint/validation_test.go
- controllers/vpcendpoint/vpcendpoint_controller.go
- deploy/crds/avo.openshift.io_vpcendpoints.yaml
- pkg/util/naming.go
- pkg/util/naming_test.go
This commit fixes a race condition during VpcEndpoint deletion when the backing CustomResources which holds the infra id is deleted before the VpcEndpoint. By storing the infra id in the VpcEndpoint's own status field, the deletion of these objects can continue regardless of whether the infrastructure or hostedcontrolplane CRs are deleted first.
[OSD-16820](https://issues.redhat.com//browse/OSD-16820)
> Store cluster infra id in .status.infraId

- controllers/vpcendpoint/helpers.go
After the bugfix in #186, cleanup is now failing with:
```json
{"level":"error","ts":"2023-06-09T17:53:30Z","msg":"Reconciler error","controller":"vpcendpoint","controllerGroup":"avo.openshift.io","controllerKind":"VpcEndpoint","vpcEndpoint":{"name":"private-hcp","namespace":"REDACTED"},"namespace":"REDACTED","name":"private-hcp","reconcileID":"af05d6d7-42f7-4bb6-8247-3f139721b3f4","error":"AWSEndpointService.hypershift.openshift.io \"private-router\" not found"}
```
In observed cases, the status field is already populated. We can ignore this error in these cases.
[OSD-16820](https://issues.redhat.com//browse/OSD-16820)
> Ignore missing awsendpointservice if status field is already set

- controllers/vpcendpoint/cleanup.go
- controllers/vpcendpoint/helpers.go
The infra name always became updated with the contents of the infrastructures CR
The existing logic (simplified) basically had it do:
```go
if vpce.Status.InfraId == "" {
// Get it from the HCP CR
} else {
// Get if from the infrastructures CR
}
```
[OSD-16820](https://issues.redhat.com//browse/OSD-16820)
> Fix logical error when setting .status.infraId

- controllers/vpcendpoint/cleanup.go
- controllers/vpcendpoint/helpers.go
Similar to #188 where this was done for .status.vpcEndpointId:
Cleanup .status.hostedZoneId and .status.securityGroupId only when the respective resources no longer exist in AWS.
[OSD-16820](https://issues.redhat.com//browse/OSD-16820)
> Continue to make cleanup more resilient

- controllers/vpcendpoint/validation.go
Reports the error reason when Route53 host record validation does not succeed.
This is an _extremely_ minor nit, but I was reviewing a case where a `vpcendpoint` was not being cleaned up, and AVO was reporting `VPCEndpoint is not in the available state` when in actual fact the VPCE was in an available state and the reason was seemingly due to something different, but not being reported as the error message itself is not respected.
> Failing route53 validation should report the reason

- hack/olm-registry/olm-artifacts-template.yaml
We were using the incorrect kind/apiVersion for successful decoding and getting this in the logs:
```json
{"level":"error","ts":"2023-07-05T17:17:40Z","logger":"setup","msg":"unable to load config file, continuing with defaults","file":"/avo/avo_config.yaml","error":"could not decode file into runtime.Object"}
```
[OSD-17334](https://issues.redhat.com//browse/OSD-17334)
> Fix bug preventing decoding of AvoConfig

- hack/olm-registry/olm-artifacts-hypershift-template.yaml
- hack/olm-registry/olm-artifacts-template-fedramp.yaml
- hack/olm-registry/olm-artifacts-template.yaml
* Restricted SCC enforcement will be added with OCP 4.14
* Updating the catalogsource to allow the operator to get deployed
* Clusters that don't support the setting (<4.12) will ignore it
Jira: [OSD-17471](https://issues.redhat.com//browse/OSD-17471)
> Make catalogsource compatible with restricted SCC enforcement

- hack/olm-registry/olm-artifacts-template.yaml
This parameter will exclude this SSS from deploying to "known" sectors, i.e. sectors that we would otherwise want to roll out progressively.
[SDCICD-991](https://issues.redhat.com//browse/SDCICD-991)
> Add KNOWN_SECTORS parameter to default HyperShift template

- hack/olm-registry/olm-artifacts-template.yaml
[SDCICD-991](https://issues.redhat.com//browse/SDCICD-991)
Tested using `oc process -f ${template}`, the original quotes resulted in:
```
values: '[''main'']'
```
While the new quotes result in:
```
values:
- main
- test
```
> Use correct syntax to supply an array of strings

- api/v1alpha2/vpcendpoint_types.go
- deploy/crds/avo.openshift.io_vpcendpoints.yaml
- deploy/crds/avo.openshift.io_vpcendpointtemplates.yaml
- pkg/secrets/secrets.go
The .spec.awsCredentialOverrideRef field already exists in our API, but previously only acts on IAM User credentials that are provided. This commit adds the ability to parse role_arn from the provided secret and perform sts:AssumeRole instead.
[OSD-18773](https://issues.redhat.com//browse/OSD-18773)
> Add a way for AVO to use sts:AssumeRole when instructed

- hack/olm-registry/olm-artifacts-hypershift-template.yaml
- hack/olm-registry/olm-artifacts-template-fedramp.yaml
- hack/olm-registry/olm-artifacts-template.yaml
These fields have never existed on the CatalogSource spec going back to OCP 4.4 and we handle this scheduling constraing within grpcPodConfig
https://docs.openshift.com/container-platform/4.14/rest_api/operatorhub_apis/catalogsource-operators-coreos-com-v1alpha1.html
[SDCICD-1178](https://issues.redhat.com//browse/SDCICD-1178)
> remove unknown fields from CatalogSource definition

- hack/tests/avo-acceptance-test.yaml
[SDCICD-1182](https://issues.redhat.com//browse/SDCICD-1182) 
The purpose of this PR is to add a small documentation in order to trigger a new hash into int.
> SDCICD-1182 - Adding documentation to trigger tekton pipelines in int

- controllers/vpcendpoint/helpers.go
- controllers/vpcendpoint/helpers_test.go
- pkg/aws_client/mock.go
For [OSD-24970](https://issues.redhat.com//browse/OSD-24970):
* updates logic for when AVO finds existing rules in an SG that do not contain a security group for the source
*  this is to accommodate for when/if a customer adds rules to an SG that does not align with the operators expectations
* updates Mock to define some "pre-existing" rules for testing this scenario
> OSD-24970: updates sg rule logic to ignore ip-source rules

- deploy/17_role.yaml
- deploy/18_rolebinding.yaml
This adds an additional Role and RoleBinding to be used by boilerplate in generation of the CSV's `spec.install.spec.permissions` field.
Reference:
https://github.com/openshift/boilerplate/blob/master/boilerplate/openshift/golang-osd-operator/csv-generate/common-generate-operator-bundle.py#L312-L331
> Add Role & RoleBinding for additional CSV permission admission

- config/templates/csv-template.yaml
Adding a namespace to the CSV template to ensure boilerplate generates non Cluster scoped permissions in the CSV
> Add Namespace and Permissions Array to CSV Template

- config/templates/csv-template.yaml
This fixes up the CSV template to be consistent with Add-On Operator:
https://github.com/openshift/addon-operator/blob/main/config/templates/csv-template.yaml#L47C7-L47C97
> Fixup CSV Template To Be Consistent with Add-On Operator

- api/v1alpha1/vpcendpoint_types.go
- deploy/crds/avo.openshift.io_vpcendpoints.yaml
This will relax required fields for v1lalpha1 CRD to workaround an issue with OLM CR to CRD validations ([OCPBUGS-45143](https://issues.redhat.com/browse/OCPBUGS-45143)). This now will match v1 with v2 required fields.
This should hopefully fix:
```
$ oc get installplan -n openshift-aws-vpce-operator install-28bhg -o yaml
...
reason: InstallComponentFailed
status: "False"
type: Installed
message: 'error validating existing CRs against new CRD''s schema for "vpcendpoints.avo.openshift.io":
error validating avo.openshift.io/v1alpha1, Kind=VpcEndpoint "ocm-staging-2f680nvupr68usru982fc94064oisj87-akanni-1039/private-hcp":
updated validation is too restrictive: [[].spec.externalNameService: Required
value, [].spec.serviceName: Required value, [].spec.subdomainName: Required value]'
```
> Relax AwsVPCEndpoint v1alpha1 CRD requirements 

- config/config.go
Configure boilerplate to generate an OLM bundle with a skip range pointing to the latest version. This will allow OLM to upgrade past broken replaces chains in which versions get abadoned without a path forward. The new OLM bundle will contain a single version, referencing the latest build with a `skipRange` to the version.
> SDE-4573: Enable OLM Skip Range

- pkg/aws_client/security_group.go
- pkg/util/naming.go
This supports additional suffixes for 4.16+ clusters. There will be follow on PRs to address unit testing and logging gaps as part of [OHSS-42748](https://issues.redhat.com//browse/OHSS-42748).
> OHSS-42748 Support Additional Security Group Name Suffixes 

- hack/olm-registry/olm-artifacts-hypershift-template.yaml
- hack/olm-registry/olm-artifacts-template.yaml
Set apply mode to CreateOrUpdate to avoid conflicts between OLM and Hive.
By default hive will perform the equivalent of a kubectl apply when syncing a SSS. Swapping to the CreateOrUpdate mode will update hive to perform a kubectl patch - and this will prevent the issues we've been seeing.
(An in depth explanation can be found here: https://issues.redhat.com/browse/HIVE-2666?focusedId=26162937&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-26162937 )
https://issues.redhat.com/browse/OSD-28836
> OSD-28836 Set applyBehavior to CreateOrUpdate

- Makefile
- controllers/vpcendpoint/helpers.go
- controllers/vpcendpoint/helpers_test.go
- controllers/vpcendpoint/validation.go
- controllers/vpcendpoint/validation_test.go
- pkg/aws_client/mock.go
- pkg/aws_client/security_group.go
- pkg/aws_client/security_group_test.go
- pkg/aws_client/subnet_test.go
- pkg/aws_client/vpc_endpoint_test.go
- pkg/util/naming.go
- pkg/util/naming_test.go
Introduced in 4.16 was a CAPI change in the aws tag key naming format. From `kubernetes.io/cluster/${infraID}` to `sigs.k8s.io/cluster-api-provider-aws/cluster/${infraID}`.
This change supports both the old ("legacy") format while also supporting the new CAPI naming scheme. This also adds additional logging and unit testing.
Fixes [OSD-29372](https://issues.redhat.com//browse/OSD-29372)
> OSD-29372 Support New CAPI AWS Tag Key Naming Format

- controllers/vpcendpoint/helpers.go
- pkg/aws_client/security_group.go
This fixes the usage of tag-key values for DescribeSecurityGroups call such that any combination of key will work. This also adds additional error returns upon unable to find the source SGs.
Tested locally against a problematic cluster.
Fixes [OSD-29372](https://issues.redhat.com//browse/OSD-29372)
> OSD-29372 Fix tag-key values for DescribeSecurityGroups

- controllers/vpcendpoint/helpers.go
In https://github.com/openshift/aws-vpce-operator/pull/143 we added some better handling for when no security groups were found in TGW account that match the filter.
Then in https://github.com/openshift/aws-vpce-operator/commit/2e85fc6e65ca0eb15b5b51caa682383faf41d6ec we added the return and error back, but now we are realizing we were implicitly relying on this "log and continue".
Add this back to fix that.
> OSD-29407: Add back log and remove early return for zero sg founds

- controllers/vpcendpoint/helpers.go
Use verbosity level V(0) when failing to find source security groups.  
V(1)  INFO level logs are not displayed in the current config.
> OSD-29407: Use logger verbosity '0' when failing to find source SGs

- controllers/vpcendpoint/validation.go
aws-vpce-operator was found to have many places in code where we log to verbosity 1 for errors, which causes them to not render to stdout and therefore are not found in Dynatrace.
> SREP-148: Ensure aws-vpce-operator is logging at verbosity 0
