.gitignore
controllers/vpcendpoint/validation.go
go.mod
go.sum

Validated it passes `./boilerplate/_lib/container-make lint`

Fix make lint errors

---

pkg/aws_client/client_test.go
pkg/aws_client/route53_hosted_zone.go
pkg/aws_client/route53_hosted_zone_test.go
pkg/aws_client/security_group.go
pkg/aws_client/security_group_test.go
pkg/aws_client/vpc_endpoint.go
pkg/util/helpers_test.go
pkg/util/naming_test.go

Also added some documentation comments for the original functions

OSD-11948 Add unit tests for AWS Security Group functions

---

hack/olm-registry/olm-artifacts-template.yaml

This adds the initial OLM template in order for AVO to be built and deployed.

[SDE-1754] Add Initial OLM Template

---

config/templates/csv-template.yaml

Adds CSV template to work with boilerplate CSV generation/deployment.

[OSD-12247] Add CSV Template for CSV generation/deployment

---

README.md
dev/README.md

Now that the manifests exist, add steps so that others can run it in a ROSA cluster

OSD-12246 Improve docs around running this operator in a ROSA cluster

---

Makefile
deploy/20_operator.yaml

Skip the bp saas file check altogether and set sts secret volume to optional.

[OSD-12247] Make and Deployment Updates

---

go.mod
go.sum

Housekeeping, ran these commands:
```bash
go get github.com/openshift/api@release-4.10
go get -u github.com/aws/aws-sdk-go
go mod tidy
```

OSD-12245 Keeping up-to-date with our dependencies

---

README.md
api/v1alpha1/vpcendpoint_types.go
deploy/crds/avo.openshift.io_vpcendpoints.yaml
dev/vpce_example.yml

* Initial pass at documentation to give a high-level overview of AVO
* Updated old demo VPCE CR since it's a cluster-scoped CRD now
* Some ticky-tacky CRD wording/validation improvements I noticed while working on documentation

OSD-12571 Documentation

---

README.md
designs/vpce_api_flexibility.md

This is the design proposal for retooling AVO so that it continues to meet the needs of FedRAMP and HyperShift as both projects grow as well as potentially other use-cases in the future.
JIRA: [OSD-13544](https://issues.redhat.com//browse/OSD-13544)
FedRAMP Design: https://docs.google.com/document/d/1QUJ6EayG8460v6B16Lni3HkuGkI5IjqH2dfbCuYluF8/edit
HyperShift Design: https://docs.google.com/document/d/1mhmVbudv4NSPf56eFr-ke-cbHpw-klkIx2-iRTmmG9k/edit#

Design proposal for improving AVO API flexibility

---

hack/olm-registry/olm-artifacts-template.yaml

Update OLM template to deploy AVO on:
- Hypershift management clusters
- Hypershift service clusters
Service & mgmt clusters are non-STS, so we can rely on CredentialsRequest!

Update OLM template for hypershift deployments

---

hack/olm-registry/olm-artifacts-template.yaml

Update operator SSS deployment to have different metadata.component-name

Update SSS metadata.name

---

pkg/aws_client/security_group.go

Breaking this piece out of #95, I was observing race conditions sometimes when creating security groups (usually it's instantaneous, but not always) and deleting security groups (sometimes it goes away and the controller was previously getting stuck as it couldn't delete a security group that no longer existed.

OHSS-13910 Resolve race conditions when creating/deleting security groups

---

deploy/18_rolebinding.yaml

Fix Role Ref

---

controllers/vpcendpoint/helpers.go

For [OSD-15112](https://issues.redhat.com//browse/OSD-15112) - this is a logic error introduced in #115

Fix logic error preventing VPC ID from being parsed

---

hack/tests/avo-acceptance-test.yaml

WIP
This adds a template for app-interface to consume over here:
https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/58155

AVO Progressive Delivery

---

hack/tests/avo-acceptance-test.yaml

* Add RBAC for service account to get/list ClusterDeployments
* Update template parameters
* Update script
Tested on hive-stage cluster using:
```
oc process -f hack/tests/avo-acceptance-test.yaml  -n cluster-scope --as=backplane-cluster-admin | oc apply -n cluster-scope --as=backplane-cluster-admin -f -
```

Test Job Updates

---

hack/tests/avo-acceptance-test.yaml

This PR Fixes the empty lines between the commnes to maintain the yaml format.

PD - Linted the avo-acceptace-test new lines.

---

hack/tests/avo-acceptance-test.yaml

Update backoffLimit back to 5.

Update backoffLimit back to 5.

---

go.mod
hack/olm-registry/olm-artifacts-template-fedramp.yaml
hack/olm-registry/olm-artifacts-template.yaml

Secondary SSS template to support acceptance controller deployments of AVO independently from the resources it manages.

OSD-15146 - Adding additional olm template to support additional operator deployment strategies

---

hack/tests/Test.md

This commit added a file under /hack/test/Test.md that will be used to trigger the progressive delivery pipelines. 
This PR will have a matching PR in the future that will be used to record a demo for the progressive delivery of Operators.

Test Progressive Delivery(1/2)

---

hack/olm-registry/olm-artifacts-template-fedramp.yaml

- removes an unused/unset variable as this is causing issues in App Interface with applying the changes

removes unused variable from fedramp template

---

hack/olm-registry/olm-artifacts-template-fedramp.yaml

- fixes bad indentation that local YAML linter decided not to catch
- please double check the rest because other linters don't seem to have a problem either, but app sre believes this is why the auto generated variables are not being processed (IMAGE_DIGEST)

fixes bad yaml spacing

---

controllers/vpcendpoint/helpers.go

This fixes an issue where no rules were being added since the source SGs for cluster nodes do not exist in the transit account.
[OSD-15465](https://issues.redhat.com/browse/OSD-15465)

Add SG Rules When No Source SGs Found

---

controllers/vpcendpoint/helpers.go
controllers/vpcendpoint/validation.go

Make SG rule creation idempotent for non-source rules.
[OSD-15465](https://issues.redhat.com/browse/OSD-15465)

Make Non-Source SG Rule Idempotent

---

osde2e/Dockerfile
osde2e/aws_vpce_operator_runner_test.go

harness is regenerated from bp. This fixed test function name.

harness regenerated from boilerplate update

---

deploy/15_clusterrole.yaml

[OSD-15666](https://issues.redhat.com//browse/OSD-15666)

Add missing vpcendpointtemplates K8s RBAC

---

controllers/vpcendpoint/cleanup.go

This commit fixes a bug where a rejected VPC Endpoint would cause the generation of a Route53 Record to fail, which was halting the deletion of a VpcEndpoint. This is fixed by not trying to generate a Route53 record and depending on the status field.
If we own a hosted zone, then just cleanup all records during deletion.
---
This is a continuation of #195 where I noticed uninstalls could still get stuck by this edge case after further testing in stage
Fixes [OSD-17219](https://issues.redhat.com//browse/OSD-17219)

Fix rejected VPCE preventing cleanup of Route53

---

build/Dockerfile
build/Dockerfile.olm-registry

[OSD-18595](https://issues.redhat.com//browse/OSD-18595)

ubi-minimal++

---

controllers/vpcendpoint/cleanup.go

Check to see if the custom domain is the same as the cluster's private domain and if so, only delete the vpce's custom domain record (not the entire zone)

OSD-18595 don't delete the cluster private domain zone on cleanup

---

controllers/vpcendpoint/cleanup.go

Main bugfix is updating the deletion flow to be based off of `.status.HostedZoneId` instead of `.spec.customDns.route53PrivateHostedZone.id` since the `status` is guaranteed to exist during Route53 deletion flows while the `spec` field is optional 
[OSD-18595](https://issues.redhat.com//browse/OSD-18595)

Obtain hosted zone id from status during deletion

---

controllers/vpcendpoint/cleanup.go

The problem:
The operator is somehow running into:
```
operation error Route 53: ChangeResourceRecordSets, https response error StatusCode: 403, RequestID: 4d4ce37d-9f4b-4d9f-a2d9-70bc616f93b0, api error AccessDenied: User: arn:aws-us-gov:sts::REDACTED:assumed-role/REDACTED is not authorized to perform: route53:ChangeResourceRecordSets on resource: arn:aws-us-gov:route53:::hostedzone/REDACTED because no identity-based policy allows the route53:ChangeResourceRecordSets action
```
and it could be because we are trying to delete an A record when one does not exist. I cannot reproduce this locally, but it seems to be safe code to remove nonetheless.
Old logic:
* If `customDns.domainName == dns.baseDomain`, then cleanup a Route53 Record
* Else try to delete the hosted zone
* and complain if …

Fix bug with invalid route53:ChangeResourceRecordSet call

---

OWNERS

[OSD-20635](https://issues.redhat.com//browse/OSD-20635)

Leaver process - bdmiller3

---

OWNERS

remove achvatal from OWNERS

---

config/templates/csv-template.yaml

Fixing indentation to match that of the [addon operator](https://github.com/openshift/addon-operator/blob/main/config/templates/csv-template.yaml#L38-L47).

Fix indentation in CSV template

---

hack/olm-registry/olm-artifacts-template.yaml

Add TechPreviewUnsafeFailForward to Hypershift SSS
https://olm.operatorframework.io/docs/advanced-tasks/unsafe-fail-forward-upgrades/

Add TechPreviewUnsafeFailForward to Hypershift SSS

---

.tekton/OWNERS
.tekton/aws-vpce-operator-pull-request.yaml
.tekton/aws-vpce-operator-push.yaml

Adding Konflux .tekton pipelines for push and pull events
Adding Owner file

Red Hat Konflux kflux-prd-rh03 update aws-vpce-operator and Adding OWNER files
